version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'python main.py'  below was in Dockerfile we moved it here 
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
    # all file connected to docker container any changes
    #  will be reflect in docker or here 
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python  consumer.py'
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: admin
      # MYSQL_USER: root
      MYSQL_PASSWORD: 9818
      MYSQL_ROOT_PASSWORD: 9818
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  
  # db:
  #   image: postgres
  #   restart: always
  #   # container_name: "db_cont"
  #   environment:
  #       - POSTGRES_USER=postgres
  #       - POSTGRES_PASSWORD=5432
  #   ports:
  #     - '5432:5433'
  #     # to map to a folder 
  #   volumes: 
  #     - .db:/var/lib/postgresql/data


# Terminal
# eventdrivenarchwithrabbitmq-queue-1    | Received in admin
# eventdrivenarchwithrabbitmq-queue-1    | b'hello'
